import { DistrictData, PriorityScoreResult } from '../scoring/priorityEngine';

export interface PolicyBriefInput {
  clusterId: string;
  problemTitle: string;
  problemSummary: string;
  category: string;
  citizensAffected: number;
  urgency: number;
  district: DistrictData;
  scoreResult: PriorityScoreResult;
  approxLocation: string;
}

export function generatePolicyBriefMarkdown(input: PolicyBriefInput): { markdown: string; validationPassed: boolean } {
  const d = input.district;
  const s = input.scoreResult;
  const capturePct = Math.round(d.estimated_reporting_capture_rate * 100);
  const effectiveImpact = Math.round(input.citizensAffected / Math.max(d.estimated_reporting_capture_rate, 0.3));
  const bplPctFormatted = (d.bpl_pct * 100).toFixed(1);
  const budgetFormatted = d.existing_budget_allocation.toLocaleString('en-IN');
  const scoreFormatted = s.priority_score.toFixed(1);
  
  const markdown = `
# JAN-SETU AI — DISTRICT PRIORITY BRIEF
**Target Cluster ID:** ${input.clusterId} | **District:** ${d.name} (${d.code}) | **Category:** ${input.category}

---

### 1. PROBLEM STATEMENT & CITIZEN SIGNAL
- **Title:** ${input.problemTitle}
- **Location:** ${input.approxLocation}
- **Direct Citizen Reports:** ${input.citizensAffected} unique Telegram submissions.
- **Reach-Adjusted Effective Impact:** ${effectiveImpact} citizens (adjusted for estimated district reporting capture rate of ${capturePct}%).

> [!NOTE]
> **Reach-adjusted estimate — not independently verifiable**
> Telegram reporting capture rate (${capturePct}%) is disclosed as a reach-correction model to avoid under-counting digitally excluded populations.

---

### 2. EXPLAINABLE PRIORITY SCORE: ${scoreFormatted} / 100
Priority score generated via JAN-SETU AI deterministic engine:

| Priority Factor | Formula Weight | Calculated Contribution | Value / Context |
| :--- | :--- | :--- | :--- |
| **Citizen Impact** | 30% | ${(s.factor_citizen_impact * 100).toFixed(1)} pts | ${input.citizensAffected} reports (${effectiveImpact} reach-adjusted) |
| **Infrastructure Deficit** | 25% | ${(s.factor_infra_deficit * 100).toFixed(1)} pts | Index: ${d.infra_deficit_score.toFixed(2)} / 1.00 |
| **Investment Gap** | 20% | ${(s.factor_investment_gap * 100).toFixed(1)} pts | Current Budget: ₹${budgetFormatted} |
| **Equity (BPL %)** | 15% | ${(s.factor_equity_bpl * 100).toFixed(1)} pts | District BPL: ${bplPctFormatted}% |
| **Urgency** | 10% | ${(s.factor_urgency * 100).toFixed(1)} pts | Urgency Index: ${(input.urgency * 100).toFixed(0)}% |

---

### 3. DATA PROVENANCE & UNCERTAINTY
- **Population:** ${d.population.toLocaleString('en-IN')} (Source: ${d.population_source}, ${d.population_as_of}) [Status: ${d.population_confidence}]
- **BPL %:** ${bplPctFormatted}% (Source: ${d.bpl_pct_source}, ${d.bpl_pct_as_of}) [Status: ${d.bpl_pct_confidence}]
- **Infrastructure Deficit:** ${d.infra_deficit_score.toFixed(2)} (Source: ${d.infra_deficit_source}, ${d.infra_deficit_as_of}) [Status: ${d.infra_deficit_confidence}]
- **Budget Allocation:** ₹${budgetFormatted} (Source: ${d.budget_source}, ${d.budget_as_of}) [Status: ${d.budget_confidence}]

${s.has_self_extracted_data ? `> [!WARNING]\n> **VERIFY BEFORE FUNDING REQUIRED**\n> Self-extracted indicator data detected in source record. Score is preserved at ${scoreFormatted}, but human data verification is required prior to fund disbursement.` : `> [!TIP]\n> Data provenance verified across primary district indicators.`}

---

### 4. RECOMMENDED ACTION & VERIFICATION PLAN
1. **Immediate Action:** Allocate priority emergency funding to resolve ${input.problemTitle} in ${input.approxLocation}.
2. **Citizen Closed-Loop:** Upon project funding, activate Telegram quorum verification across reporting citizens (${input.citizensAffected} direct participants).
3. **Quorum & Evidence Rule:** Require citizen quorum confirmation + human photo review prior to marking project outcome as VERIFIED.

*Brief generated by JAN-SETU AI Number-Safe Policy Engine — Provenance Tracked.*
`.trim();

  // Approved numeric set for strict number safety validation
  const approvedNumbers = new Set<string>([
    String(input.citizensAffected),
    String(effectiveImpact),
    String(capturePct),
    String(d.population),
    String(d.population.toLocaleString('en-IN')),
    String(bplPctFormatted),
    String((d.bpl_pct * 100).toFixed(0)),
    String(d.infra_deficit_score.toFixed(2)),
    String(d.infra_deficit_score),
    String(d.existing_budget_allocation),
    String(budgetFormatted),
    String(scoreFormatted),
    String(Math.round(s.priority_score)),
    String((s.factor_citizen_impact * 100).toFixed(1)),
    String((s.factor_infra_deficit * 100).toFixed(1)),
    String((s.factor_investment_gap * 100).toFixed(1)),
    String((s.factor_equity_bpl * 100).toFixed(1)),
    String((s.factor_urgency * 100).toFixed(1)),
    String((input.urgency * 100).toFixed(0)),
    '30', '25', '20', '15', '10', '90', '100', '0.3', '0.42', '1', '2', '3', '4'
  ]);

  // Extract currency, percentage, or formatted numbers from markdown
  const matches = markdown.match(/₹?[\d,]+(\.\d+)?%?/g) || [];
  let validationPassed = true;

  for (const rawNumStr of matches) {
    const cleanNumStr = rawNumStr.replace(/[₹%,]/g, '').trim();
    if (cleanNumStr.length > 0 && !approvedNumbers.has(cleanNumStr) && !approvedNumbers.has(rawNumStr)) {
      const val = parseFloat(cleanNumStr);
      if (!isNaN(val) && val > 4 && !approvedNumbers.has(String(Math.round(val)))) {
        validationPassed = false;
        console.warn(`[Number Safety Validation] Unverified number detected: ${rawNumStr}`);
      }
    }
  }

  return {
    markdown,
    validationPassed
  };
}
